### ISSUE TITLE
include param doesn't work

### ISSUE THREAD

**Issue by bmac** [endpoints/example#1]
Doing a fresh install. If I try to visit an url with some include params like [http://localhost:8080/authors?include=books](http://localhost:8080/authors?include=book)  I get an error.

```
TypeError: Object #<Object> has no method 'indexOf'
   at /Users/bmac/code/example/node_modules/endpoints-source-bookshelf/index.js:92:29
   at Array.filter (native)
   at Source.read (/Users/bmac/code/example/node_modules/endpoints-source-bookshelf/index.js:91:25)
   at /Users/bmac/code/example/node_modules/endpoints/modules/request/index.js:95:12
   at Layer.handle [as handle_request] (/Users/bmac/code/example/node_modules/express/lib/router/layer.js:82:5)
   at next (/Users/bmac/code/example/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/Users/bmac/code/example/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/Users/bmac/code/example/node_modules/express/lib/router/layer.js:82:5)
   at /Users/bmac/code/example/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/Users/bmac/code/example/node_modules/express/lib/router/index.js:321:12)
   at next (/Users/bmac/code/example/node_modules/express/lib/router/index.js:261:10)
   at Function.proto.handle (/Users/bmac/code/example/node_modules/express/lib/router/index.js:166:3)
   at router (/Users/bmac/code/example/node_modules/express/lib/router/index.js:35:12)
   at Layer.handle [as handle_request] (/Users/bmac/code/example/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/bmac/code/example/node_modules/express/lib/router/index.js:302:13)
   at /Users/bmac/code/example/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/Users/bmac/code/example/node_modules/express/lib/router/index.js:321:12)
   at next (/Users/bmac/code/example/node_modules/express/lib/router/index.js:261:10)
   at jsonParser (/Users/bmac/code/example/node_modules/body-parser/lib/types/json.js:83:36)
   at Layer.handle [as handle_request] (/Users/bmac/code/example/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/bmac/code/example/node_modules/express/lib/router/index.js:302:13)
   at /Users/bmac/code/example/node_modules/express/lib/router/index.js:270:7
```

**Comment by tkellen** [comment]
fixed!
